# ===================================================================
# Merkezi Konfigürasyon Dosyası - JetX Tahmin Sistemi (v2)
# ===================================================================

# -------------------------------------------------------------------
# Veritabanı ve Dosya Yolları
# -------------------------------------------------------------------
paths:
  database: "data/jetx_data.db"
  models_dir: "trained_models"
  log_file: "jetx_prediction.log"
  cache_dir: "data/cache" # Yeni önbellek dizini

# -------------------------------------------------------------------
# Genel Eğitim ve HPO Ayarları
# -------------------------------------------------------------------
training:
  hpo_trials: 15 # Her model için denenecek HPO kombinasyon sayısı
  default_epochs: 75
  batch_size: 32
  validation_split: 0.15
  min_data_points: 500
  threshold: 1.5

# ===================================================================
# Model Yapılandırmaları (Merkezileştirilmiş)
# ===================================================================
models:
  N-Beats:
    default_params:
      sequence_length: 300
      hidden_size: 512
      num_stacks: 4
      num_blocks: 4
      learning_rate: 0.0005
      crash_weight: 3.0
      train_params:
        epochs: 75
        batch_size: 32
        validation_split: 0.15
        verbose: true
    hpo_space:
      learning_rate: { type: 'float', low: 0.00001, high: 0.01, log: false }
      hidden_size: { type: 'categorical', choices: [128, 256, 512] }
      num_stacks: { type: 'int', low: 2, high: 5 }
      num_blocks: { type: 'int', low: 2, high: 5 }

  TFT:
    default_params:
      sequence_length: 250
      hidden_size: 256
      num_heads: 8
      num_layers: 3
      learning_rate: 0.0005
      crash_weight: 5.0
      train_params:
        epochs: 60
        batch_size: 16
        validation_split: 0.15
        verbose: true
    hpo_space:
      learning_rate: { type: 'float', low: 0.00001, high: 0.01, log: false }
      hidden_size: { type: 'categorical', choices: [64, 128, 256] }
      num_heads: { type: 'categorical', choices: [4, 8] }
      num_layers: { type: 'int', low: 1, high: 3 }

  LSTM:
    default_params:
      sequence_length: 200
      hidden_size: 256 # lstm_units'e haritalanır
      num_layers: 3
      learning_rate: 0.0005
      crash_weight: 5.0
      train_params:
        epochs: 80
        batch_size: 32
        validation_split: 0.15
        verbose: true
    hpo_space:
      learning_rate: { type: 'float', low: 0.00001, high: 0.01, log: false }
      hidden_size: { type: 'categorical', choices: [128, 256, 512] }
      num_layers: { type: 'int', low: 1, high: 4 }

# ===================================================================
# Diğer Ayarlar
# ===================================================================
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
